# Generated by Django 2.2.2 on 2019-12-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
