# Generated by Django 2.2.2 on 2019-12-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20191214_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='playerid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
